#pragma once

// TODO: Describe versioning
#define PHOENIXOFHP_STL_VECTOR_VERSION_MAJOR 0
#define PHOENIXOFHP_STL_VECTOR_VERSION_MINOR 0
#define PHOENIXOFHP_STL_VECTOR_VERSION_PATCH 1

constexpr static inline float PHOENIXOFHP_STL_VECTOR_REALLOCATE_FACTOR_BASE = 2;
constexpr static inline float PHOENIXOFHP_STL_VECTOR_REALLOCATE_FACTOR_EXP = 1;
constexpr static inline float PHOENIXOFHP_STL_VECTOR_REALLOCATE_FACTOR_MAX = 2;

static_assert(
    PHOENIXOFHP_STL_VECTOR_REALLOCATE_FACTOR_BASE > 0.0f,
    "PHOENIXOFHP_STL_VECTOR: REALLOCATE_FACTOR_BASE must be positive");
static_assert(PHOENIXOFHP_STL_VECTOR_REALLOCATE_FACTOR_EXP > 0.0f,
              "PHOENIXOFHP_STL_VECTOR: REALLOCATE_FACTOR_EXP must be positive");
static_assert(PHOENIXOFHP_STL_VECTOR_REALLOCATE_FACTOR_MAX > 0.0f,
              "PHOENIXOFHP_STL_VECTOR: REALLOCATE_FACTOR_MAX must be positive");
